'use client';
import classNames from 'classnames';
import './globals.css';
import { createContext, useContext } from 'react';

const themes = {
  light: {
    background: 'bg-white',
    text: 'text-black',
    btn: 'bg-blue-800',
    input: 'bg-gray-800',
    white: 'white',
  },
  dark: {
    background: 'bg-gray-800',
    text: 'text-white',
    btn: 'bg-gray-600',
    input: 'bg-white',
    black: 'black',
  },
};

//createContext 함수를 사용
export const themeContext = createContext(themes.light);

const ToggleButton = () => {
  const theme = useContext(themeContext);
  return <button className={classNames(theme.btn, 'py-2 px-5 rounded-lg flex mt-4')}>색상변경</button>;
};

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  const theme = useContext(themeContext);
  return (
    <html lang='ko'>
      <head>
        <title>TodoList</title>
      </head>

      <body>{children}</body>
    </html>
  );
}
